DROP DATABASE IF EXISTS ORDERS;
CREATE DATABASE ORDERS;
USE ORDERS;

CREATE TABLE USER_ORDER(
ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
ITEM_NAME VARCHAR (100) NOT NULL UNIQUE,
PRICE DOUBLE NOT NULL,
BUYER_NAME CHAR (32) NOT NULL,
MAIL_ADDRESS VARCHAR(500) NOT NULL,
PRIMARY KEY(ID)
);